### PR TITLE
Add Configuration

### PR DESCRIPTION
**Pull request by tmtmtmtm**
Allow configuration of each Check via a YAML config file. This file iskeyed by the "moniker" of the Check, and can provide options on how it should be applied.

As an example, allow the WikidataIdentifiers check to vary the column name it's interested in, and whether capitalisation of the column is important.

# Note to reviewer

I haven't added anything to the README about this yet, as that will be best handled when we actually provide orchestration for finding and running checks (#2)

### CODE REVIEW

**Comment by alexdutton** [comment]
I know it's only been added as an example, but can we have the changes to `WikidataIdentifiers` use `WIKIDATA` and `fixed` as defaults, as that's the convention established in https://github.com/everypolitician/commons-builder/wiki/Boundary-pull-request-review-checklist ?

**Comment by alexdutton** [comment]
I'm also wondering whether it's worth supporting configuring a single check with multiple sets of parameters, which might necessitate a different approach (but I guess we can work that out later if/when we have a use-case).

**Comment by tmtmtmtm** [comment]
@alexsdutton I'm not sure that a fixed case "WIKIDATA" is a sensible default for what to check against. That may be what we have in those boundary files, but that seems to me to be the more exceptional case, that you'd expect to have to specify for those cases, than the norm. 

Note also that this check will work just fine against those files as-is. Checking that the column *name* is all in upper-case would be a different Check.

**Comment by tmtmtmtm** [comment]
> I'm also wondering whether it's worth supporting configuring a single check with multiple sets of parameters, which might necessitate a different approach (but I guess we can work that out later if/when we have a use-case).

I'm not entirely sure I'm following this suggestion, but at the moment each Check is responsible for parsing the config it was given, which will just be a lump of YAML. The Check I've implemented here expects a single hash, but another Check could just as happily want a list of hashes, or something else entirely. 

It's definitely worth thinking early about whether we're boxing ourselves into a corner in the interface, so if there are specific cases you're thinking of that might turn out to be tricksy to refactor to later without changing how existing code interacts with this, it would be good to consider them.

**Comment by alexdutton** [comment]
Okay, I'll add a check for CSV column names. And we'll see about cross-file checking later.

**Review by alexdutton — APPROVED** [review]

**Pull request merged**
